import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { RotateCcw, Trash2 } from 'lucide-react';
import { automaticItemMonthly, baseDiskCount, formatBRL, isUpgradeCompatible, normalizeProposalItem, upgradeQuantity, type ServerModel, type ServerModality, type ServerProposalItem, type ServerUpgrade } from '@/lib/serverRental';

interface Props { items:ServerProposalItem[];models:ServerModel[];upgrades:ServerUpgrade[];modality:ServerModality;onChange:(items:ServerProposalItem[])=>void }
export default function ServerItemsEditor({items,models,upgrades,modality,onChange}:Props){
  const {toast}=useToast();
  const commit=(index:number,next:ServerProposalItem)=>{const normalized=normalizeProposalItem(next);onChange(items.map((item,i)=>i===index?{...normalized,mensalidade:normalized.preco_manual?normalized.mensalidade:automaticItemMonthly(normalized)}:item));};
  const add=(modelId:string)=>{const model=models.find(m=>m.id===modelId);if(!model)return;onChange([...items,{id:crypto.randomUUID(),model,quantidade:1,upgrades:[],mensalidade:Number(model.mensalidade_base),preco_manual:false}]);};
  const replaceModel=(index:number,modelId:string)=>{const model=models.find(m=>m.id===modelId);if(!model)return;const current=normalizeProposalItem(items[index]);const kept=current.upgrades.filter(u=>isUpgradeCompatible(u,model,modality));const removed=current.upgrades.filter(u=>!kept.some(k=>k.id===u.id));commit(index,{...current,model,upgrades:kept,preco_manual:false});if(removed.length)toast({title:'Adicionais incompatíveis removidos',description:`${removed.map(u=>u.nome).join(', ')}: não compatível com ${model.nome}.`});};
  const setMemory=(index:number,value:string)=>{const current=normalizeProposalItem(items[index]);const without=current.upgrades.filter(u=>u.categoria!=='memoria');const selected=upgrades.find(u=>u.id===value);commit(index,{...current,upgrades:selected?[...without,{...selected,quantidade:1}]:without,preco_manual:false});};
  const setUpgrade=(index:number,upgrade:ServerUpgrade,enabled:boolean)=>{const current=normalizeProposalItem(items[index]);const next=enabled?[...current.upgrades.filter(u=>u.id!==upgrade.id),{...upgrade,quantidade:1}]:current.upgrades.filter(u=>u.id!==upgrade.id);commit(index,{...current,upgrades:next,preco_manual:false});};
  const setUpgradeQty=(index:number,upgrade:ServerUpgrade,quantity:number)=>{const current=normalizeProposalItem(items[index]);const next=current.upgrades.filter(u=>u.id!==upgrade.id);if(quantity>0)next.push({...upgrade,quantidade});commit(index,{...current,upgrades:next,preco_manual:false});};
  return <div className="space-y-4">
    <div><Label>Adicionar servidor do catálogo</Label><Select onValueChange={add}><SelectTrigger><SelectValue placeholder="Selecione um modelo"/></SelectTrigger><SelectContent>{models.filter(m=>m.ativo).map(m=><SelectItem key={m.id} value={m.id}>{m.nome} · {formatBRL(m.mensalidade_base)}/mês</SelectItem>)}</SelectContent></Select></div>
    {items.map((raw,index)=>{const item=normalizeProposalItem(raw);const compatible=upgrades.filter(u=>isUpgradeCompatible(u,item.model,modality));const memories=compatible.filter(u=>u.categoria==='memoria').sort((a,b)=>Number(a.capacidade_gb)-Number(b.capacidade_gb));const storage=compatible.filter(u=>u.categoria==='armazenamento');const others=compatible.filter(u=>u.categoria!=='memoria'&&u.categoria!=='armazenamento');const memory=item.upgrades.find(u=>u.categoria==='memoria');const totalRam=Number(item.model.ram_base_gb)+(Number(memory?.capacidade_gb)||0);const baseBays=baseDiskCount(item.model.storage_base);const usedBays=baseBays+item.upgrades.filter(u=>u.categoria==='armazenamento').reduce((s,u)=>s+upgradeQuantity(u),0);const free=Math.max(0,Number(item.model.baias)-usedBays);return <div key={item.id} className="space-y-4 rounded-md border p-4">
      <div className="flex justify-between gap-3"><div className="flex-1"><Label>Modelo</Label><Select value={item.model.id} onValueChange={v=>replaceModel(index,v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{models.filter(m=>m.ativo||m.id===item.model.id).map(m=><SelectItem key={m.id} value={m.id}>{m.nome}</SelectItem>)}</SelectContent></Select><p className="mt-1 text-xs text-muted-foreground">{item.model.cpu} · {item.model.storage_base}</p></div><Button type="button" size="icon" variant="ghost" title="Remover servidor" onClick={()=>onChange(items.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4"/></Button></div>
      <div className="grid gap-3 sm:grid-cols-2"><div><Label>Quantidade de servidores</Label><Input type="number" min={1} value={item.quantidade} onChange={e=>commit(index,{...item,quantidade:Math.max(1,Number(e.target.value))})}/></div><div><Label>Mensalidade por unidade</Label><div className="flex gap-2"><Input type="number" min={0} step="0.01" value={item.mensalidade} onChange={e=>commit(index,{...item,mensalidade:Number(e.target.value),preco_manual:true})}/><Button type="button" size="icon" variant="outline" title="Redefinir para automático" disabled={!item.preco_manual} onClick={()=>commit(index,{...item,preco_manual:false})}><RotateCcw className="h-4 w-4"/></Button></div><small className="text-muted-foreground">{item.preco_manual?'Valor manual':'Calculado automaticamente'}</small></div></div>
      <div className="rounded-md bg-muted p-3"><Label>RAM adicional</Label><div className="mt-1 grid items-center gap-3 sm:grid-cols-2"><Select value={memory?.id||'none'} onValueChange={v=>setMemory(index,v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Nenhuma</SelectItem>{memories.map(u=><SelectItem key={u.id} value={u.id}>+{u.capacidade_gb}GB · {formatBRL(u.mensalidade)}/mês</SelectItem>)}</SelectContent></Select><p className="text-sm">RAM total: <b>{item.model.ram_base_gb}GB base{memory?` + ${memory.capacidade_gb}GB`:''} = {totalRam}GB</b> (máx. {item.model.ram_max_gb||'—'}GB)</p></div></div>
      <div><div className="flex items-center justify-between gap-2"><Label>Armazenamento adicional</Label><span className="text-xs text-muted-foreground">Baias: {usedBays} de {item.model.baias} em uso</span></div><div className="mt-2 grid gap-2 sm:grid-cols-2">{storage.map(up=>{const selected=item.upgrades.find(u=>u.id===up.id);const current=selected?upgradeQuantity(selected):0;const max=current+free;return <div key={up.id} className="flex items-center justify-between gap-3 rounded border p-2 text-sm"><span><b>{up.nome}</b><small className="block text-muted-foreground">{formatBRL(up.mensalidade)} · {up.tipo_cobranca==='mensal'?'mensal':'única'}</small></span><Input aria-label={`Quantidade de ${up.nome}`} className="w-20" type="number" min={0} max={max} value={current} onChange={e=>setUpgradeQty(index,up,Math.min(max,Math.max(0,Number(e.target.value))))}/></div>})}{!storage.length&&<p className="text-sm text-muted-foreground">Nenhum disco compatível.</p>}</div></div>
      <div><Label>Serviços e demais adicionais</Label><div className="mt-2 grid gap-2 sm:grid-cols-2">{others.map(up=>{const selected=item.upgrades.find(u=>u.id===up.id);return <div key={up.id} className="flex items-center gap-2 rounded border p-2 text-sm"><Checkbox checked={Boolean(selected)} onCheckedChange={v=>setUpgrade(index,up,v===true)}/><span className="min-w-0 flex-1"><b>{up.nome}</b><small className="block text-muted-foreground">{formatBRL(up.mensalidade)} · {up.tipo_cobranca==='mensal'?'mensal':'única'}</small></span>{up.permite_quantidade&&selected&&<Input aria-label={`Quantidade de ${up.nome}`} className="w-20" type="number" min={1} value={upgradeQuantity(selected)} onChange={e=>setUpgradeQty(index,up,Math.max(1,Number(e.target.value)))}/>}</div>})}</div></div>
    </div>})}
    {!items.length&&<p className="rounded-md border border-dashed py-8 text-center text-sm text-muted-foreground">Nenhum servidor adicionado.</p>}
    <div className="grid gap-2 rounded-md bg-muted p-4 sm:grid-cols-2"><p><span className="text-xs text-muted-foreground">TOTAL MENSAL</span><strong className="block text-lg text-primary">{formatBRL(items.reduce((s,i)=>s+i.mensalidade*i.quantidade,0))}</strong></p><p><span className="text-xs text-muted-foreground">TOTAL IMPLANTAÇÃO</span><strong className="block text-lg text-primary">{formatBRL(items.reduce((s,i)=>s+i.upgrades.filter(u=>u.tipo_cobranca==='unica').reduce((x,u)=>x+Number(u.mensalidade)*upgradeQuantity(u)*i.quantidade,0),0))}</strong></p></div>
  </div>;
}
