import jsPDF from 'jspdf';
import { DELTA7_LOGO_DARK_SMALL, DELTA7_LOGO_WHITE_SMALL } from '@/assets/delta7LogoSmallBase64';
import { formatBRL, renderClause, serverConfiguration, upgradeQuantity, type ServerClause, type ServerModality, type ServerPlan, type ServerProposalContent, type ServerProposalItem } from '@/lib/serverRental';

export interface ServerProposalPdfData { proposalNumber:string; generatedAt:string; validityDays:number; clientName:string; clientDocument?:string; clientContact?:string; clientEmail?:string; clientPhone?:string; clientAddress?:string; salesRepName:string; salesRepEmail?:string; modalidade:ServerModality; items:ServerProposalItem[]; plans:ServerPlan[]; clauses:ServerClause[]; customContent:ServerProposalContent; notes?:string; integrityHash:string }
const NAVY:[number,number,number]=[10,31,68], ORANGE:[number,number,number]=[232,119,34], WHITE:[number,number,number]=[255,255,255], INK:[number,number,number]=[26,37,64], MUTED:[number,number,number]=[100,116,139], LIGHT:[number,number,number]=[241,245,249];
const PW=210, PH=297, ML=18, CW=174;
const txt=(d:jsPDF,s:string,x:number,y:number,size=9,color=INK,style:'normal'|'bold'|'italic'='normal',align:'left'|'right'|'center'='left')=>{d.setFont('helvetica',style);d.setFontSize(size);d.setTextColor(...color);d.text(s,x,y,{align});};
const rect=(d:jsPDF,x:number,y:number,w:number,h:number,c:[number,number,number])=>{d.setFillColor(...c);d.rect(x,y,w,h,'F');};
const date=(s:string)=>new Date(s).toLocaleDateString('pt-BR');
function header(d:jsPDF,r:ServerProposalPdfData){try{d.addImage(DELTA7_LOGO_DARK_SMALL,'JPEG',ML,7,30,9);}catch{} txt(d,'Locação de Servidores',ML+CW,12,8,MUTED,'normal','right');txt(d,r.proposalNumber,ML+CW,17,9,NAVY,'bold','right');d.setDrawColor(...ORANGE);d.line(ML,21,ML+CW,21);}
function title(d:jsPDF,label:string,y:number){txt(d,label.toUpperCase(),ML,y,13,NAVY,'bold');rect(d,ML,y+3,18,1,ORANGE);return y+10;}
function paragraph(d:jsPDF,text:string,y:number,width=CW,color=INK){const lines=d.splitTextToSize(text,width);d.setFont('helvetica','normal');d.setFontSize(9);d.setTextColor(...color);d.text(lines,ML,y);return y+lines.length*4.5;}
function ensure(d:jsPDF,y:number,needed:number,r:ServerProposalPdfData){if(y+needed<PH-18)return y;d.addPage();header(d,r);return 30;}
async function build(r:ServerProposalPdfData){const d=new jsPDF({unit:'mm',format:'a4'});rect(d,0,0,PW,PH,NAVY);try{d.addImage(DELTA7_LOGO_WHITE_SMALL,'JPEG',ML,14,38,12);}catch{} rect(d,ML,78,22,1.5,ORANGE);txt(d,'PROPOSTA COMERCIAL',ML,91,9,[148,163,184]);txt(d,'LOCAÇÃO',ML,119,39,WHITE,'bold');txt(d,'de Servidores.',ML,139,31,ORANGE,'bold');paragraph(d,r.customContent.coverSubtitle,157,130,[190,200,218]);txt(d,r.modalidade==='on_premise'?'SERVIDOR NO SEU LOCAL':'SERVIDOR DEDICADO DELTA7',ML,184,11,WHITE,'bold');txt(d,'PREPARADO PARA',ML,250,7,[148,163,184]);txt(d,r.clientName,ML,258,13,WHITE,'bold');txt(d,`${r.proposalNumber} · ${date(r.generatedAt)} · Validade ${r.validityDays} dias`,ML,266,9,[190,200,218]);
  d.addPage();header(d,r);let y=31;y=title(d,'Identificação e solução',y);const info=[['Cliente',r.clientName],['Documento',r.clientDocument||'—'],['Contato',[r.clientContact,r.clientPhone].filter(Boolean).join(' · ')||'—'],['E-mail',r.clientEmail||'—'],['Endereço',r.clientAddress||'—'],['Executivo',r.salesRepName]];info.forEach(([l,v],i)=>{rect(d,ML,y,CW,8,i%2?WHITE:LIGHT);txt(d,l,ML+2,y+5.5,8,NAVY,'bold');txt(d,String(v),ML+36,y+5.5,8,INK);y+=8});y+=8;y=title(d,'Resumo da solução',y);y=paragraph(d,r.modalidade==='on_premise'?r.customContent.onPremiseSummary:r.customContent.dedicatedSummary,y)+8;y=title(d,'Equipamentos',y);const monthly=r.items.reduce((s,i)=>s+i.mensalidade*i.quantidade,0);r.items.forEach((item,index)=>{y=ensure(d,y,24,r);rect(d,ML,y,CW,8,NAVY);txt(d,`${item.quantidade}x ${item.model.nome}`,ML+3,y+5.5,9,WHITE,'bold');txt(d,formatBRL(item.mensalidade*item.quantidade)+'/mês',ML+CW-3,y+5.5,9,ORANGE,'bold','right');y+=8;y=paragraph(d,serverConfiguration(item),y+5,CW-6)+2;const extras=item.upgrades.filter(u=>u.categoria!=='memoria'&&u.categoria!=='armazenamento');if(extras.length)y=paragraph(d,'Adicionais: '+extras.map(u=>`${upgradeQuantity(u)>1?`${upgradeQuantity(u)}x `:''}${u.nome}`).join(', '),y,CW-6)+3;if(index%2===0)rect(d,ML,y-1,CW,.3,LIGHT)});rect(d,ML,y,CW,10,LIGHT);txt(d,'TOTAL MENSAL',ML+3,y+6.5,9,NAVY,'bold');txt(d,formatBRL(monthly),ML+CW-3,y+6.5,11,ORANGE,'bold','right');y+=18;
  const setup=r.items.flatMap(i=>i.upgrades.filter(u=>u.tipo_cobranca==='unica').map(u=>({...u,qty:i.quantidade*upgradeQuantity(u)})));if(setup.length){y=ensure(d,y,30,r);y=title(d,'Taxas de implantação',y);setup.forEach(u=>{txt(d,`${u.qty}x ${u.nome}`,ML,y,8,INK);txt(d,formatBRL(u.mensalidade*u.qty),ML+CW,y,8,NAVY,'bold','right');y+=6});txt(d,'TOTAL '+formatBRL(setup.reduce((s,u)=>s+u.mensalidade*u.qty,0)),ML+CW,y,9,ORANGE,'bold','right');y+=10}
  y=ensure(d,y,52,r);y=title(d,'Planos de contratação',y);const w=CW/Math.max(r.plans.length,1);r.plans.forEach((p,i)=>{const x=ML+i*w;rect(d,x,y,w-2,35,p.prazo===36?ORANGE:NAVY);txt(d,`${p.prazo} MESES`,x+(w-2)/2,y+8,9,WHITE,'bold','center');txt(d,formatBRL(p.mensal),x+(w-2)/2,y+19,13,WHITE,'bold','center');txt(d,`Total ${formatBRL(p.mensal*p.prazo)}`,x+(w-2)/2,y+27,7,WHITE,'normal','center');if(p.prazo===36)txt(d,'MELHOR CUSTO',x+(w-2)/2,y+33,6,WHITE,'bold','center')});y+=45;
  y=ensure(d,y,40,r);y=title(d,r.customContent.includedTitle,y);const included=[...new Set(r.items.flatMap(i=>i.upgrades.filter(u=>u.categoria==='servico').map(u=>u.nome)))];(included.length?included:['Equipamentos configurados conforme esta proposta','Implantação e acompanhamento Delta7']).forEach(v=>{rect(d,ML,y-3,2,5,ORANGE);txt(d,v,ML+5,y,8,INK);y+=7});
  d.addPage();header(d,r);y=31;y=title(d,'Condições contratuais',y);r.clauses.filter(c=>c.active).forEach((c,i)=>{const rendered=renderClause(c),lines=d.splitTextToSize(rendered,CW-8),h=12+lines.length*4;y=ensure(d,y,h,r);txt(d,`${i+1}. ${c.title}`,ML,y,9,NAVY,'bold');d.setFontSize(8);d.setTextColor(...INK);d.text(lines,ML+4,y+6);y+=h});if(r.notes){y=ensure(d,y,24,r);y=title(d,'Observações',y);y=paragraph(d,r.notes,y)+6}y=ensure(d,y,52,r);y=title(d,'Aceite',y);y=paragraph(d,r.customContent.acceptanceText,y)+18;d.setDrawColor(...NAVY);d.line(ML,y,ML+70,y);d.line(ML+CW-70,y,ML+CW,y);txt(d,'CONTRATANTE',ML+35,y+6,8,MUTED,'bold','center');txt(d,'DELTA7 TECNOLOGIA',ML+CW-35,y+6,8,MUTED,'bold','center');txt(d,'Local e data: _______________________________________________',ML,y+20,8,MUTED);txt(d,`Integridade SHA-256: ${r.integrityHash}`,ML,PH-12,6,MUTED);return d;}
export async function downloadServerProposalPdf(data:ServerProposalPdfData){const d=await build(data);d.save(`Proposta_Servidores_${data.clientName.replace(/\s+/g,'_')}_${data.proposalNumber}.pdf`)}
export async function previewServerProposalPdf(data:ServerProposalPdfData){const d=await build(data);return d.output('datauristring')}